all: build

Objects/Train1: Trains/Generated/Train1.c Generic/step.h
	@echo Building Train1...
	@gcc -c -O2 -Wall Trains/Generated/Train1.c -o Objects/Train1

Objects/Train2: Trains/Generated/Train2.c Generic/step.h
	@echo Building Train2...
	@gcc -c -O2 -Wall Trains/Generated/Train2.c -o Objects/Train2

Objects/Train3: Trains/Generated/Train3.c Generic/step.h
	@echo Building Train3...
	@gcc -c -O2 -Wall Trains/Generated/Train3.c -o Objects/Train3

Objects/Train4: Trains/Generated/Train4.c Generic/step.h
	@echo Building Train4...
	@gcc -c -O2 -Wall Trains/Generated/Train4.c -o Objects/Train4

Objects/Train5: Trains/Generated/Train5.c Generic/step.h
	@echo Building Train5...
	@gcc -c -O2 -Wall Trains/Generated/Train5.c -o Objects/Train5

Objects/Train6: Trains/Generated/Train6.c Generic/step.h
	@echo Building Train6...
	@gcc -c -O2 -Wall Trains/Generated/Train6.c -o Objects/Train6

Objects/Train7: Trains/Generated/Train7.c Generic/step.h
	@echo Building Train7...
	@gcc -c -O2 -Wall Trains/Generated/Train7.c -o Objects/Train7

Objects/Train8: Trains/Generated/Train8.c Generic/step.h
	@echo Building Train8...
	@gcc -c -O2 -Wall Trains/Generated/Train8.c -o Objects/Train8

Objects/Train9: Trains/Generated/Train9.c Generic/step.h
	@echo Building Train9...
	@gcc -c -O2 -Wall Trains/Generated/Train9.c -o Objects/Train9

Objects/Train10: Trains/Generated/Train10.c Generic/step.h
	@echo Building Train10...
	@gcc -c -O2 -Wall Trains/Generated/Train10.c -o Objects/Train10

Objects/Train11: Trains/Generated/Train11.c Generic/step.h
	@echo Building Train11...
	@gcc -c -O2 -Wall Trains/Generated/Train11.c -o Objects/Train11

Objects/Train12: Trains/Generated/Train12.c Generic/step.h
	@echo Building Train12...
	@gcc -c -O2 -Wall Trains/Generated/Train12.c -o Objects/Train12

Objects/Train13: Trains/Generated/Train13.c Generic/step.h
	@echo Building Train13...
	@gcc -c -O2 -Wall Trains/Generated/Train13.c -o Objects/Train13

Objects/Train14: Trains/Generated/Train14.c Generic/step.h
	@echo Building Train14...
	@gcc -c -O2 -Wall Trains/Generated/Train14.c -o Objects/Train14

Objects/Train15: Trains/Generated/Train15.c Generic/step.h
	@echo Building Train15...
	@gcc -c -O2 -Wall Trains/Generated/Train15.c -o Objects/Train15

Objects/Train16: Trains/Generated/Train16.c Generic/step.h
	@echo Building Train16...
	@gcc -c -O2 -Wall Trains/Generated/Train16.c -o Objects/Train16

Objects/Train17: Trains/Generated/Train17.c Generic/step.h
	@echo Building Train17...
	@gcc -c -O2 -Wall Trains/Generated/Train17.c -o Objects/Train17

Objects/Train18: Trains/Generated/Train18.c Generic/step.h
	@echo Building Train18...
	@gcc -c -O2 -Wall Trains/Generated/Train18.c -o Objects/Train18

Objects/Train19: Trains/Generated/Train19.c Generic/step.h
	@echo Building Train19...
	@gcc -c -O2 -Wall Trains/Generated/Train19.c -o Objects/Train19

Objects/Train20: Trains/Generated/Train20.c Generic/step.h
	@echo Building Train20...
	@gcc -c -O2 -Wall Trains/Generated/Train20.c -o Objects/Train20

Objects/Train21: Trains/Generated/Train21.c Generic/step.h
	@echo Building Train21...
	@gcc -c -O2 -Wall Trains/Generated/Train21.c -o Objects/Train21

Objects/Train22: Trains/Generated/Train22.c Generic/step.h
	@echo Building Train22...
	@gcc -c -O2 -Wall Trains/Generated/Train22.c -o Objects/Train22

Objects/Train23: Trains/Generated/Train23.c Generic/step.h
	@echo Building Train23...
	@gcc -c -O2 -Wall Trains/Generated/Train23.c -o Objects/Train23

Objects/Train24: Trains/Generated/Train24.c Generic/step.h
	@echo Building Train24...
	@gcc -c -O2 -Wall Trains/Generated/Train24.c -o Objects/Train24

Objects/Train25: Trains/Generated/Train25.c Generic/step.h
	@echo Building Train25...
	@gcc -c -O2 -Wall Trains/Generated/Train25.c -o Objects/Train25

Objects/Train26: Trains/Generated/Train26.c Generic/step.h
	@echo Building Train26...
	@gcc -c -O2 -Wall Trains/Generated/Train26.c -o Objects/Train26

Objects/Train27: Trains/Generated/Train27.c Generic/step.h
	@echo Building Train27...
	@gcc -c -O2 -Wall Trains/Generated/Train27.c -o Objects/Train27

Objects/Train28: Trains/Generated/Train28.c Generic/step.h
	@echo Building Train28...
	@gcc -c -O2 -Wall Trains/Generated/Train28.c -o Objects/Train28

Objects/Train29: Trains/Generated/Train29.c Generic/step.h
	@echo Building Train29...
	@gcc -c -O2 -Wall Trains/Generated/Train29.c -o Objects/Train29

Objects/Train30: Trains/Generated/Train30.c Generic/step.h
	@echo Building Train30...
	@gcc -c -O2 -Wall Trains/Generated/Train30.c -o Objects/Train30

Objects/Gate: Gates/Generated/Gate.c Generic/step.h
	@echo Building Gate...
	@gcc -c -O2 -Wall Gates/Generated/Gate.c -o Objects/Gate

runnable: runnable.c Generic/step.h
	@echo Building Runnable...
	@gcc -O2 runnable.c Objects/Train1 Objects/Train2 Objects/Train3 Objects/Train4 Objects/Train5 Objects/Train6 Objects/Train7 Objects/Train8 Objects/Train9 Objects/Train10 Objects/Train11 Objects/Train12 Objects/Train13 Objects/Train14 Objects/Train15 Objects/Train16 Objects/Train17 Objects/Train18 Objects/Train19 Objects/Train20 Objects/Train21 Objects/Train22 Objects/Train23 Objects/Train24 Objects/Train25 Objects/Train26 Objects/Train27 Objects/Train28 Objects/Train29 Objects/Train30 Objects/Gate -o runnable

dir_build:
	@mkdir -p Objects

build: dir_build Objects/Train1 Objects/Train2 Objects/Train3 Objects/Train4 Objects/Train5 Objects/Train6 Objects/Train7 Objects/Train8 Objects/Train9 Objects/Train10 Objects/Train11 Objects/Train12 Objects/Train13 Objects/Train14 Objects/Train15 Objects/Train16 Objects/Train17 Objects/Train18 Objects/Train19 Objects/Train20 Objects/Train21 Objects/Train22 Objects/Train23 Objects/Train24 Objects/Train25 Objects/Train26 Objects/Train27 Objects/Train28 Objects/Train29 Objects/Train30 Objects/Gate runnable

clean:
	@echo Removing compiled binaries...
	@rm -r Objects/Train1
	@rm -r Objects/Train2
	@rm -r Objects/Train3
	@rm -r Objects/Train4
	@rm -r Objects/Train5
	@rm -r Objects/Train6
	@rm -r Objects/Train7
	@rm -r Objects/Train8
	@rm -r Objects/Train9
	@rm -r Objects/Train10
	@rm -r Objects/Train11
	@rm -r Objects/Train12
	@rm -r Objects/Train13
	@rm -r Objects/Train14
	@rm -r Objects/Train15
	@rm -r Objects/Train16
	@rm -r Objects/Train17
	@rm -r Objects/Train18
	@rm -r Objects/Train19
	@rm -r Objects/Train20
	@rm -r Objects/Train21
	@rm -r Objects/Train22
	@rm -r Objects/Train23
	@rm -r Objects/Train24
	@rm -r Objects/Train25
	@rm -r Objects/Train26
	@rm -r Objects/Train27
	@rm -r Objects/Train28
	@rm -r Objects/Train29
	@rm -r Objects/Train30
	@rm -r Objects/Gate
	@rm -r runnable

