all: build

Objects/Train1: Trains/Generated/Train1.c Generic/step.h
	@echo Building Train1...
	@cl /c /O2 Trains/Generated/Train1.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train1

Objects/Train2: Trains/Generated/Train2.c Generic/step.h
	@echo Building Train2...
	@cl /c /O2 Trains/Generated/Train2.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train2

Objects/Train3: Trains/Generated/Train3.c Generic/step.h
	@echo Building Train3...
	@cl /c /O2 Trains/Generated/Train3.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train3

Objects/Train4: Trains/Generated/Train4.c Generic/step.h
	@echo Building Train4...
	@cl /c /O2 Trains/Generated/Train4.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train4

Objects/Train5: Trains/Generated/Train5.c Generic/step.h
	@echo Building Train5...
	@cl /c /O2 Trains/Generated/Train5.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train5

Objects/Train6: Trains/Generated/Train6.c Generic/step.h
	@echo Building Train6...
	@cl /c /O2 Trains/Generated/Train6.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train6

Objects/Train7: Trains/Generated/Train7.c Generic/step.h
	@echo Building Train7...
	@cl /c /O2 Trains/Generated/Train7.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train7

Objects/Train8: Trains/Generated/Train8.c Generic/step.h
	@echo Building Train8...
	@cl /c /O2 Trains/Generated/Train8.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train8

Objects/Train9: Trains/Generated/Train9.c Generic/step.h
	@echo Building Train9...
	@cl /c /O2 Trains/Generated/Train9.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train9

Objects/Train10: Trains/Generated/Train10.c Generic/step.h
	@echo Building Train10...
	@cl /c /O2 Trains/Generated/Train10.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train10

Objects/Train11: Trains/Generated/Train11.c Generic/step.h
	@echo Building Train11...
	@cl /c /O2 Trains/Generated/Train11.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train11

Objects/Train12: Trains/Generated/Train12.c Generic/step.h
	@echo Building Train12...
	@cl /c /O2 Trains/Generated/Train12.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train12

Objects/Train13: Trains/Generated/Train13.c Generic/step.h
	@echo Building Train13...
	@cl /c /O2 Trains/Generated/Train13.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train13

Objects/Train14: Trains/Generated/Train14.c Generic/step.h
	@echo Building Train14...
	@cl /c /O2 Trains/Generated/Train14.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train14

Objects/Train15: Trains/Generated/Train15.c Generic/step.h
	@echo Building Train15...
	@cl /c /O2 Trains/Generated/Train15.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train15

Objects/Train16: Trains/Generated/Train16.c Generic/step.h
	@echo Building Train16...
	@cl /c /O2 Trains/Generated/Train16.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train16

Objects/Train17: Trains/Generated/Train17.c Generic/step.h
	@echo Building Train17...
	@cl /c /O2 Trains/Generated/Train17.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train17

Objects/Train18: Trains/Generated/Train18.c Generic/step.h
	@echo Building Train18...
	@cl /c /O2 Trains/Generated/Train18.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train18

Objects/Train19: Trains/Generated/Train19.c Generic/step.h
	@echo Building Train19...
	@cl /c /O2 Trains/Generated/Train19.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train19

Objects/Train20: Trains/Generated/Train20.c Generic/step.h
	@echo Building Train20...
	@cl /c /O2 Trains/Generated/Train20.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train20

Objects/Train21: Trains/Generated/Train21.c Generic/step.h
	@echo Building Train21...
	@cl /c /O2 Trains/Generated/Train21.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train21

Objects/Train22: Trains/Generated/Train22.c Generic/step.h
	@echo Building Train22...
	@cl /c /O2 Trains/Generated/Train22.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train22

Objects/Train23: Trains/Generated/Train23.c Generic/step.h
	@echo Building Train23...
	@cl /c /O2 Trains/Generated/Train23.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train23

Objects/Train24: Trains/Generated/Train24.c Generic/step.h
	@echo Building Train24...
	@cl /c /O2 Trains/Generated/Train24.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train24

Objects/Train25: Trains/Generated/Train25.c Generic/step.h
	@echo Building Train25...
	@cl /c /O2 Trains/Generated/Train25.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train25

Objects/Train26: Trains/Generated/Train26.c Generic/step.h
	@echo Building Train26...
	@cl /c /O2 Trains/Generated/Train26.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train26

Objects/Train27: Trains/Generated/Train27.c Generic/step.h
	@echo Building Train27...
	@cl /c /O2 Trains/Generated/Train27.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train27

Objects/Train28: Trains/Generated/Train28.c Generic/step.h
	@echo Building Train28...
	@cl /c /O2 Trains/Generated/Train28.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train28

Objects/Train29: Trains/Generated/Train29.c Generic/step.h
	@echo Building Train29...
	@cl /c /O2 Trains/Generated/Train29.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train29

Objects/Train30: Trains/Generated/Train30.c Generic/step.h
	@echo Building Train30...
	@cl /c /O2 Trains/Generated/Train30.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Train30

Objects/Gate: Gates/Generated/Gate.c Generic/step.h
	@echo Building Gate...
	@cl /c /O2 Gates/Generated/Gate.c /FoC:\Users\nall426\git\DATE2016_codegen\examples\train_and_gate\Objects\Gate

runnable: runnable.c Generic/step.h
	@echo Building Runnable...
	@cl /O2 runnable.c Objects/Train1.obj Objects/Train2.obj Objects/Train3.obj Objects/Train4.obj Objects/Train5.obj Objects/Train6.obj Objects/Train7.obj Objects/Train8.obj Objects/Train9.obj Objects/Train10.obj Objects/Train11.obj Objects/Train12.obj Objects/Train13.obj Objects/Train14.obj Objects/Train15.obj Objects/Train16.obj Objects/Train17.obj Objects/Train18.obj Objects/Train19.obj Objects/Train20.obj Objects/Train21.obj Objects/Train22.obj Objects/Train23.obj Objects/Train24.obj Objects/Train25.obj Objects/Train26.obj Objects/Train27.obj Objects/Train28.obj Objects/Train29.obj Objects/Train30.obj Objects/Gate.obj /Fe

build: Objects/Train1 Objects/Train2 Objects/Train3 Objects/Train4 Objects/Train5 Objects/Train6 Objects/Train7 Objects/Train8 Objects/Train9 Objects/Train10 Objects/Train11 Objects/Train12 Objects/Train13 Objects/Train14 Objects/Train15 Objects/Train16 Objects/Train17 Objects/Train18 Objects/Train19 Objects/Train20 Objects/Train21 Objects/Train22 Objects/Train23 Objects/Train24 Objects/Train25 Objects/Train26 Objects/Train27 Objects/Train28 Objects/Train29 Objects/Train30 Objects/Gate runnable

clean:
	@echo Removing compiled binaries...
	@rm -r Objects/Train1
	@rm -r Objects/Train2
	@rm -r Objects/Train3
	@rm -r Objects/Train4
	@rm -r Objects/Train5
	@rm -r Objects/Train6
	@rm -r Objects/Train7
	@rm -r Objects/Train8
	@rm -r Objects/Train9
	@rm -r Objects/Train10
	@rm -r Objects/Train11
	@rm -r Objects/Train12
	@rm -r Objects/Train13
	@rm -r Objects/Train14
	@rm -r Objects/Train15
	@rm -r Objects/Train16
	@rm -r Objects/Train17
	@rm -r Objects/Train18
	@rm -r Objects/Train19
	@rm -r Objects/Train20
	@rm -r Objects/Train21
	@rm -r Objects/Train22
	@rm -r Objects/Train23
	@rm -r Objects/Train24
	@rm -r Objects/Train25
	@rm -r Objects/Train26
	@rm -r Objects/Train27
	@rm -r Objects/Train28
	@rm -r Objects/Train29
	@rm -r Objects/Train30
	@rm -r Objects/Gate
	@rm -r runnable

